steps:
  # Step 1: Build using dynamic variables
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/aura-ecom:latest', '.']

  # Step 2: Push using dynamic variables
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/aura-ecom:latest']

  # Step 3: Deploy using dynamic variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aura-ecom-service'
      - '--image'
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/aura-ecom:latest'
      - '--region'
      - '${_LOCATION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - "^|^DB_URI=your_uri|JWT_SECRET=your_secret" # ... (rest of your env vars)

# Set default values just in case
substitutions:
  _LOCATION: us-central1
  _REPO_NAME: aura-repo

options:
  logging: CLOUD_LOGGING_ONLY
