steps:
  # Step 1: Build using dynamic variables
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/aura-ecom:latest', '.']

  # Step 2: Push using dynamic variables
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/aura-ecom:latest']

  # Step 3: Deploy with ALL Environment Variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aura-ecom-service'
      - '--image'
      - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/aura-ecom:latest'
      - '--region'
      - '${_LOCATION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      # This block contains ALL your required credentials
      - "^|^DB_URI=mongodb+srv://pushpajohn:john%402@e-com.nkbqpap.mongodb.net/E-Comm?retryWrites=true&w=majority&appName=E-Comm|JWT_SECRET_KEY=pushsecretkey|JWT_EXPIRE=3d|SMTP_SERVICE=gmail|SMTP_MAIL=pushpakalajohn.2@gmail.com|SMTP_PASSWORD=kifz auvr uimg dvic|RAZORPAY_KEY_ID=rzp_test_RQEYzWx6ZaLAaY|RAZORPAY_KEY_SECRET=WBJYRq2r4TmhPRhrAiYgMi05|NODE_ENV=production"

# Fallback values for manual runs
substitutions:
  _LOCATION: us-central1
  _REPO_NAME: aura-repo

options:
  logging: CLOUD_LOGGING_ONLY
